
export const OSD_RECORD_FLYCSTATE = {
0: "Manual",
1: "Atti",
2: "Atti_CL",
3: "Atti_Hover",
4: "Hover",
5: "GPS_Blake",
6: "GPS_Atti",
7: "GPS_CL",
8: "GPS_HomeLock",
9: "GPS_HotPoint",
10: "AssistedTakeoff",
11: "AutoTakeoff",
12: "AutoLanding",
13: "AttiLanding",
14: "NaviGo",
15: "GoHome",
16: "ClickGo",
17: "Joystick",
18: "GPS_Atti_Wristband",
19: "Cinematic",
23: "Atti_Limited",
24: "GPS_Atti_Limited",
25: "NaviMissionFollow",
26: "NaviSubMode_Tracking",
27: "NaviSubMode_Pointing",
28: "PANO",
29: "Farming",
30: "FPV",
31: "Sport",
32: "Novice",
33: "ForceLanding",
35: "TerrainTracking",
36: "NaviAdvGoHome",
37: "NaviAdvLanding",
38: "TripodGPS",
39: "TrackHeadlock",
41: "EngineStart",
43: "GentleGPS",
};

export const OSD_RECORD_FLYCCOMMAND = {
1: "AutoFly",
2: "AutoLanding",
3: "HomePointNow",
4: "HomePointHot",
5: "HomePointLock",
6: "GoHome",
7: "StartMotor",
8: "StopMotor",
9: "Calibration",
10: "DeformProtecClose",
11: "DeformProtecOpen",
12: "DropGoHome",
13: "DropTakeOff",
14: "DropLanding",
15: "DynamicHomePointOpen",
16: "DynamicHomePointClose",
17: "FollowFunctionOpen",
18: "FollowFunctionClose",
19: "IOCOpen",
20: "IOCClose",
21: "DropCalibration",
22: "PackMode",
23: "UnPackMode",
24: "EnterManualMode",
25: "StopDeform",
28: "DownDeform",
29: "UpDeform",
30: "ForceLanding",
31: "ForceLanding2",
};

export const OSD_RECORD_GROUND_OR_SKY = {
0: "Ground",
1: "Ground",
2: "Sky",
3: "Sky",
};

export const OSD_RECORD_GO_HOME_STATUS = {
0: "Standby",
1: "Preascending",
2: "Align",
3: "Ascending",
4: "Cruise",
5: "Braking",
6: "Bypassing",
};

export const OSD_RECORD_BATTERY_TYPE = {
1: "Non Smart",
2: "Smart",
};
export const OSD_RECORD_FLIGHT_ACTION = {
0: "None",
1: "Warning Power Go Home",
2: "Warning Power Landing",
3: "Smart Power Go Home",
4: "Smart Power Landing",
5: "Low Voltage Landing",
6: "Low Voltage GoHome",
7: "Serious Low Voltage Landing",
8: "RC_Onekey Go Home",
9: "RC_Assistant Takeoff",
10: "RC_Auto Takeoff",
11: "RC_Auto Landing",
12: "AppAuto Go Home",
13: "AppAuto Landing",
14: "AppAuto Takeoff",
15: "Out Of Control Go Home",
16: "Api Auto Takeoff",
17: "Api Auto Landing",
18: "Api Auto GoHome",
19: "Avoid Ground Landing",
20: "Airport Avoid Landing",
21: "Too Close Go Home Landing",
22: "Too Far Go Home Landing",
23: "App_WP_Mission",
24: "WP_Auto Takeoff",
25: "Go Home Avoid",
26: "GoHome Finish",
27: "Vert Low Limit Landing",
28: "Battery Force Landing",
29: "MC_ProtectGoHome",
30: "Motor block Landing",
31: "App Request Force Landing",
32: "Fake Battery Landing",
33: "RTH_ComingObstacleLanding",
34: "IMU Error RTH",
};

export const OSD_RECORD_MOTOR_START_FAILED_CAUSE = {
0: "None",
1: "CompassError",
2: "AssistantProtected",
3: "DeviceLocked",
4: "DistanceLimit",
5: "IMUNeedCalibration",
6: "IMUSNError",
7: "IMUWarning",
8: "CompassCalibrating",
9: "AttiError",
10: "NoviceProtected",
11: "BatteryCellError",
12: "BatteryCommuniteError",
13: "SeriousLowVoltage",
14: "SeriousLowPower",
15: "LowVoltage",
16: "TempureVolLow",
17: "SmartLowToLand",
18: "BatteryNotReady",
19: "SimulatorMode",
20: "PackMode",
21: "AttitudeAbnormal",
22: "UnActive",
23: "FlyForbiddenError",
24: "BiasError",
25: "EscError",
26: "ImuInitError",
27: "SystemUpgrade",
28: "SimulatorStarted",
29: "ImuingError",
30: "AttiAngleOver",
31: "GyroscopeError",
32: "AcceleratorError",
33: "CompassFailed",
34: "BarometerError",
35: "BarometerNegative",
36: "CompassBig",
37: "GyroscopeBiasBig",
38: "AcceleratorBiasBig",
39: "CompassNoiseBig",
40: "BarometerNoiseBig",
41: "InvalidSn",
44: "FlashOperating",
45: "GPSdisconnect",
47: "SDCardException",
61: "IMUNoconnection",
62: "RCCalibration",
63: "RCCalibrationException",
64: "RCCalibrationUnfinished",
65: "RCCalibrationException2",
66: "RCCalibrationException3",
67: "AircraftTypeMismatch",
68: "FoundUnfinishedModule",
70: "CyroAbnormal",
71: "BaroAbnormal",
72: "CompassAbnormal",
73: "GPS_Abnormal",
74: "NS_Abnormal",
75: "TopologyAbnormal",
76: "RC_NeedCali",
77: "InvalidFloat",
78: "M600_BAT_TOO_LITTLE",
79: "M600_BAT_AUTH_ERR",
80: "M600_BAT_COMM_ERR",
81: "M600_BAT_DIF_VOLT_LARGE_1",
82: "M600_BAT_DIF_VOLT_LARGE_2",
83: "InvalidVersion",
84: "GimbalGyroAbnormal",
85: "GimbalESC_PitchNonData",
86: "GimbalESC_RollNonData",
87: "GimbalESC_YawNonData",
88: "GimbalFirmwIsUpdating",
89: "GimbalDisorder",
90: "GimbalPitchShock",
91: "GimbalRollShock",
92: "GimbalYawShock",
93: "IMUcCalibrationFinished",
101: "BattVersionError",
102: "RTK_BadSignal",
103: "RTK_DeviationError",
112: "ESC_Calibrating",
113: "GPS_SignInvalid",
114: "GimbalIsCalibrating",
115: "LockByApp",
116: "StartFlyHeightError",
117: "ESC_VersionNotMatch",
118: "IMU_ORI_NotMatch",
119: "StopByApp",
120: "CompassIMU_ORI_NotMatch",
122: "CompassIMU_ORI_NotMatch",
123: "Battery Over Temperature",
124: "Battery nstall Error",
125: "Be Impact",
};

export const OSD_RECORD_NON_GPS_CAUSE = {
0: "Already",
1: "Forbid",
2: "Gps Num Not Enough",
3: "Gps Hdop Large",
4: "Gps Position NonMatch",
5: "Speed Error Large",
6: "Yaw Error Large",
7: "Compass Error Large",
};

export const OSD_RECORD_DRONE_TYPE = {
1: "Inspire 1",
2: "P3 Advanced",
3: "P3 Professional",
4: "P3 Standard",
5: "OpenFrame",
6: "AceOne",
7: "WKM",
8: "Naza",
9: "A2",
10: "A3",
11: "P4",
14: "Matrice 600",
15: "P3 4K",
16: "Mavic",
17: "Inspire 2",
18: "P4 Professional",
20: "N3",
21: "Spark",
23: "Matrice 600 Pro",
24: "Mavic Air",
25: "Matrice 200",
27: "P4 Advanced",
28: "Matrice 210",
29: "P3SE",
30: "Matrice 210MTK",
};

export const OSD_RECORD_IMU_INIT_FAIL_REASON = {
0: "MonitorError",
1: "CollectingData",
3: "AcceDead",
4: "Compass Dead",
5: "Barometer Dead",
6: "Barometer Negative",
7: "Compass Mod Too Large",
8: "Gyro Bias Too Large",
9: "Acce Bias Too Large",
10: "Compass Noise Too Large",
11: "Barometer Noise Too Large",
12: "Waiting McStationary",
13: "Acce Move Too Large",
14: "Mc Header Moved",
15: "Mc Vibrated",
};

export const OSD_RECORD_MOTOR_FAIL_REASON = {
94: "Takeoff Exception",
95: "ESC_Stall Near Ground",
96: "ESC_Unbalance On Ground",
97: "ESC_PART_EMPTY On Ground",
98: "Engine Start Failed",
99: "Auto Takeoff LaunchFailed",
100: "Roll Over On Ground",
};

export const OSD_RECORD_CTRL_DEVICE = {
0: "RC",
1: "App",
2: "OnboardDevice",
3: "Camera",
};

export const GIMBAL_MODE = {
0: "YawNoFollow",
1: "FPV",
2: "YawFollow",
};

export const SMART_BATTERY_STATUS = {
0: "None",
};

export const SMART_BATTERY_GO_HOME_STATUS = {
0: "Non Go Home",
1: "Go Home",
2: "Go Home Already",
};

export const DEFORM_STATUS = {
1: "FoldComplete",
2: "Folding",
3: "StretchComplete",
4: "Stretching",
5: "StopDeformation",
};

export const DEFORM_MODE = {
0: "Pack",
1: "Protect",
2: "Normal",
};

export const HOME_IOC_MODE = {
1: "Course Lock",
2: "Home Lock",
3: "Hotspot Surround",
};
export const RECOVERY_DRONE_TYPE = {
1: "Inspire 1",
2: "P3 Standard",
3: "P3 Advanced",
4: "P3 Professional",
5: "OSMO",
6: "Matrice 100",
7: "P4",
8: "LB2",
9: "Inspire 1 Pro",
10: "A3",
11: "Matrice 600",
12: "P3 4K",
13: "Mavic Pro",
14: "Zenmuse XT",
15: "Inspire 1 RAW",
16: "A2",
17: "Inspire 2",
18: "OSMO Pro",
19: "OSMO Raw",
20: "SMO+",
21: "Mavic",
22: "OSMO Mobile",
23: "OrangeCV600",
24: "P4 Professional",
25: "N3 FC",
26: "Spark",
27: "Matrice 600 Pro",
28: "P4 Advanced",
30: "AG405",
31: "Matrice 200",
33: "Matrice 210",
34: "Matrice 210RTK",
38: "Mavic Air",
};

export const RECOVERY_APP_TYPE = {
1: "iOS",
2: "Android",
};

export const DETAILS_APP_TYPE = {
1: "iOS",
2: "Android",
};

export const NO_MATCH = "Other";
